.\" -*- nroff -*-
.TH ptscotch_esmumps 1 "April 2009" "Scotch"
.SH NAME
ptscotch_esmumps \- ptscotch command
.SH SYNOPSIS
.B ptscotch_esmumps
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR ptscotch_esmumps
command.

You can find information in the scotch manual and on the scotch web
page http://www.labri.fr/perso/pelegrin/scotch/ and project page
http://gforge.inria.fr/projects/scotch/.

.SH AUTHOR
The Debian Scientific Computing Team
